language: python
python:
  - "2.7"
install:
  # dependencies
  - pip install -r requirements/common.txt --process-dependency-links
  # `coveralls` to run tests with coverage
  - pip install coveralls
script:
  # all the tests
  - coverage run --source=hamam run_tests.py
after_success:
  - coveralls
notifications:
  # send the notification about the build results
  email:
    recipients:
      - web-dev@txtr.com
    on_success: change
    on_failure: change
